// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ownship.proto

#ifndef PROTOBUF_ownship_2eproto__INCLUDED
#define PROTOBUF_ownship_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ownship_2eproto();
void protobuf_AssignDesc_ownship_2eproto();
void protobuf_ShutdownFile_ownship_2eproto();

class OwnshipReport;

// ===================================================================

class OwnshipReport : public ::google::protobuf::Message {
 public:
  OwnshipReport();
  virtual ~OwnshipReport();

  OwnshipReport(const OwnshipReport& from);

  inline OwnshipReport& operator=(const OwnshipReport& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OwnshipReport& default_instance();

  void Swap(OwnshipReport* other);

  // implements Message ----------------------------------------------

  OwnshipReport* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OwnshipReport& from);
  void MergeFrom(const OwnshipReport& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required sfixed64 timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline ::google::protobuf::int64 timestamp() const;
  inline void set_timestamp(::google::protobuf::int64 value);

  // required float ownship_latitude = 2;
  inline bool has_ownship_latitude() const;
  inline void clear_ownship_latitude();
  static const int kOwnshipLatitudeFieldNumber = 2;
  inline float ownship_latitude() const;
  inline void set_ownship_latitude(float value);

  // required float ownship_longitude = 3;
  inline bool has_ownship_longitude() const;
  inline void clear_ownship_longitude();
  static const int kOwnshipLongitudeFieldNumber = 3;
  inline float ownship_longitude() const;
  inline void set_ownship_longitude(float value);

  // required sfixed32 ownship_altitude = 4;
  inline bool has_ownship_altitude() const;
  inline void clear_ownship_altitude();
  static const int kOwnshipAltitudeFieldNumber = 4;
  inline ::google::protobuf::int32 ownship_altitude() const;
  inline void set_ownship_altitude(::google::protobuf::int32 value);

  // required float north = 5;
  inline bool has_north() const;
  inline void clear_north();
  static const int kNorthFieldNumber = 5;
  inline float north() const;
  inline void set_north(float value);

  // required float east = 6;
  inline bool has_east() const;
  inline void clear_east();
  static const int kEastFieldNumber = 6;
  inline float east() const;
  inline void set_east(float value);

  // required float down = 7;
  inline bool has_down() const;
  inline void clear_down();
  static const int kDownFieldNumber = 7;
  inline float down() const;
  inline void set_down(float value);

  // @@protoc_insertion_point(class_scope:OwnshipReport)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_ownship_latitude();
  inline void clear_has_ownship_latitude();
  inline void set_has_ownship_longitude();
  inline void clear_has_ownship_longitude();
  inline void set_has_ownship_altitude();
  inline void clear_has_ownship_altitude();
  inline void set_has_north();
  inline void clear_has_north();
  inline void set_has_east();
  inline void clear_has_east();
  inline void set_has_down();
  inline void clear_has_down();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 timestamp_;
  float ownship_latitude_;
  float ownship_longitude_;
  ::google::protobuf::int32 ownship_altitude_;
  float north_;
  float east_;
  float down_;
  friend void  protobuf_AddDesc_ownship_2eproto();
  friend void protobuf_AssignDesc_ownship_2eproto();
  friend void protobuf_ShutdownFile_ownship_2eproto();

  void InitAsDefaultInstance();
  static OwnshipReport* default_instance_;
};
// ===================================================================


// ===================================================================

// OwnshipReport

// required sfixed64 timestamp = 1;
inline bool OwnshipReport::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OwnshipReport::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OwnshipReport::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OwnshipReport::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 OwnshipReport::timestamp() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.timestamp)
  return timestamp_;
}
inline void OwnshipReport::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.timestamp)
}

// required float ownship_latitude = 2;
inline bool OwnshipReport::has_ownship_latitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OwnshipReport::set_has_ownship_latitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OwnshipReport::clear_has_ownship_latitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OwnshipReport::clear_ownship_latitude() {
  ownship_latitude_ = 0;
  clear_has_ownship_latitude();
}
inline float OwnshipReport::ownship_latitude() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.ownship_latitude)
  return ownship_latitude_;
}
inline void OwnshipReport::set_ownship_latitude(float value) {
  set_has_ownship_latitude();
  ownship_latitude_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.ownship_latitude)
}

// required float ownship_longitude = 3;
inline bool OwnshipReport::has_ownship_longitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OwnshipReport::set_has_ownship_longitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OwnshipReport::clear_has_ownship_longitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OwnshipReport::clear_ownship_longitude() {
  ownship_longitude_ = 0;
  clear_has_ownship_longitude();
}
inline float OwnshipReport::ownship_longitude() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.ownship_longitude)
  return ownship_longitude_;
}
inline void OwnshipReport::set_ownship_longitude(float value) {
  set_has_ownship_longitude();
  ownship_longitude_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.ownship_longitude)
}

// required sfixed32 ownship_altitude = 4;
inline bool OwnshipReport::has_ownship_altitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OwnshipReport::set_has_ownship_altitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OwnshipReport::clear_has_ownship_altitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OwnshipReport::clear_ownship_altitude() {
  ownship_altitude_ = 0;
  clear_has_ownship_altitude();
}
inline ::google::protobuf::int32 OwnshipReport::ownship_altitude() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.ownship_altitude)
  return ownship_altitude_;
}
inline void OwnshipReport::set_ownship_altitude(::google::protobuf::int32 value) {
  set_has_ownship_altitude();
  ownship_altitude_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.ownship_altitude)
}

// required float north = 5;
inline bool OwnshipReport::has_north() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OwnshipReport::set_has_north() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OwnshipReport::clear_has_north() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OwnshipReport::clear_north() {
  north_ = 0;
  clear_has_north();
}
inline float OwnshipReport::north() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.north)
  return north_;
}
inline void OwnshipReport::set_north(float value) {
  set_has_north();
  north_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.north)
}

// required float east = 6;
inline bool OwnshipReport::has_east() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OwnshipReport::set_has_east() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OwnshipReport::clear_has_east() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OwnshipReport::clear_east() {
  east_ = 0;
  clear_has_east();
}
inline float OwnshipReport::east() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.east)
  return east_;
}
inline void OwnshipReport::set_east(float value) {
  set_has_east();
  east_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.east)
}

// required float down = 7;
inline bool OwnshipReport::has_down() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OwnshipReport::set_has_down() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OwnshipReport::clear_has_down() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OwnshipReport::clear_down() {
  down_ = 0;
  clear_has_down();
}
inline float OwnshipReport::down() const {
  // @@protoc_insertion_point(field_get:OwnshipReport.down)
  return down_;
}
inline void OwnshipReport::set_down(float value) {
  set_has_down();
  down_ = value;
  // @@protoc_insertion_point(field_set:OwnshipReport.down)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ownship_2eproto__INCLUDED
