// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radar.proto

#ifndef PROTOBUF_radar_2eproto__INCLUDED
#define PROTOBUF_radar_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_radar_2eproto();
void protobuf_AssignDesc_radar_2eproto();
void protobuf_ShutdownFile_radar_2eproto();

class RadarReport;

// ===================================================================

class RadarReport : public ::google::protobuf::Message {
 public:
  RadarReport();
  virtual ~RadarReport();

  RadarReport(const RadarReport& from);

  inline RadarReport& operator=(const RadarReport& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarReport& default_instance();

  void Swap(RadarReport* other);

  // implements Message ----------------------------------------------

  RadarReport* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadarReport& from);
  void MergeFrom(const RadarReport& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required sfixed64 timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline ::google::protobuf::int64 timestamp() const;
  inline void set_timestamp(::google::protobuf::int64 value);

  // required float range = 2;
  inline bool has_range() const;
  inline void clear_range();
  static const int kRangeFieldNumber = 2;
  inline float range() const;
  inline void set_range(float value);

  // required float azimuth = 3;
  inline bool has_azimuth() const;
  inline void clear_azimuth();
  static const int kAzimuthFieldNumber = 3;
  inline float azimuth() const;
  inline void set_azimuth(float value);

  // required float elevation = 4;
  inline bool has_elevation() const;
  inline void clear_elevation();
  static const int kElevationFieldNumber = 4;
  inline float elevation() const;
  inline void set_elevation(float value);

  // required sfixed32 id = 5;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 5;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required float north = 6;
  inline bool has_north() const;
  inline void clear_north();
  static const int kNorthFieldNumber = 6;
  inline float north() const;
  inline void set_north(float value);

  // required float east = 7;
  inline bool has_east() const;
  inline void clear_east();
  static const int kEastFieldNumber = 7;
  inline float east() const;
  inline void set_east(float value);

  // required float down = 8;
  inline bool has_down() const;
  inline void clear_down();
  static const int kDownFieldNumber = 8;
  inline float down() const;
  inline void set_down(float value);

  // required float latitude = 9;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 9;
  inline float latitude() const;
  inline void set_latitude(float value);

  // required float longitude = 10;
  inline bool has_longitude() const;
  inline void clear_longitude();
  static const int kLongitudeFieldNumber = 10;
  inline float longitude() const;
  inline void set_longitude(float value);

  // required sfixed32 altitude = 11;
  inline bool has_altitude() const;
  inline void clear_altitude();
  static const int kAltitudeFieldNumber = 11;
  inline ::google::protobuf::int32 altitude() const;
  inline void set_altitude(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RadarReport)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_range();
  inline void clear_has_range();
  inline void set_has_azimuth();
  inline void clear_has_azimuth();
  inline void set_has_elevation();
  inline void clear_has_elevation();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_north();
  inline void clear_has_north();
  inline void set_has_east();
  inline void clear_has_east();
  inline void set_has_down();
  inline void clear_has_down();
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_longitude();
  inline void clear_has_longitude();
  inline void set_has_altitude();
  inline void clear_has_altitude();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 timestamp_;
  float range_;
  float azimuth_;
  float elevation_;
  ::google::protobuf::int32 id_;
  float north_;
  float east_;
  float down_;
  float latitude_;
  float longitude_;
  ::google::protobuf::int32 altitude_;
  friend void  protobuf_AddDesc_radar_2eproto();
  friend void protobuf_AssignDesc_radar_2eproto();
  friend void protobuf_ShutdownFile_radar_2eproto();

  void InitAsDefaultInstance();
  static RadarReport* default_instance_;
};
// ===================================================================


// ===================================================================

// RadarReport

// required sfixed64 timestamp = 1;
inline bool RadarReport::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadarReport::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadarReport::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadarReport::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 RadarReport::timestamp() const {
  // @@protoc_insertion_point(field_get:RadarReport.timestamp)
  return timestamp_;
}
inline void RadarReport::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.timestamp)
}

// required float range = 2;
inline bool RadarReport::has_range() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadarReport::set_has_range() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadarReport::clear_has_range() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadarReport::clear_range() {
  range_ = 0;
  clear_has_range();
}
inline float RadarReport::range() const {
  // @@protoc_insertion_point(field_get:RadarReport.range)
  return range_;
}
inline void RadarReport::set_range(float value) {
  set_has_range();
  range_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.range)
}

// required float azimuth = 3;
inline bool RadarReport::has_azimuth() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RadarReport::set_has_azimuth() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RadarReport::clear_has_azimuth() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RadarReport::clear_azimuth() {
  azimuth_ = 0;
  clear_has_azimuth();
}
inline float RadarReport::azimuth() const {
  // @@protoc_insertion_point(field_get:RadarReport.azimuth)
  return azimuth_;
}
inline void RadarReport::set_azimuth(float value) {
  set_has_azimuth();
  azimuth_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.azimuth)
}

// required float elevation = 4;
inline bool RadarReport::has_elevation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RadarReport::set_has_elevation() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RadarReport::clear_has_elevation() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RadarReport::clear_elevation() {
  elevation_ = 0;
  clear_has_elevation();
}
inline float RadarReport::elevation() const {
  // @@protoc_insertion_point(field_get:RadarReport.elevation)
  return elevation_;
}
inline void RadarReport::set_elevation(float value) {
  set_has_elevation();
  elevation_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.elevation)
}

// required sfixed32 id = 5;
inline bool RadarReport::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RadarReport::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RadarReport::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RadarReport::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RadarReport::id() const {
  // @@protoc_insertion_point(field_get:RadarReport.id)
  return id_;
}
inline void RadarReport::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.id)
}

// required float north = 6;
inline bool RadarReport::has_north() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RadarReport::set_has_north() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RadarReport::clear_has_north() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RadarReport::clear_north() {
  north_ = 0;
  clear_has_north();
}
inline float RadarReport::north() const {
  // @@protoc_insertion_point(field_get:RadarReport.north)
  return north_;
}
inline void RadarReport::set_north(float value) {
  set_has_north();
  north_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.north)
}

// required float east = 7;
inline bool RadarReport::has_east() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RadarReport::set_has_east() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RadarReport::clear_has_east() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RadarReport::clear_east() {
  east_ = 0;
  clear_has_east();
}
inline float RadarReport::east() const {
  // @@protoc_insertion_point(field_get:RadarReport.east)
  return east_;
}
inline void RadarReport::set_east(float value) {
  set_has_east();
  east_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.east)
}

// required float down = 8;
inline bool RadarReport::has_down() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RadarReport::set_has_down() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RadarReport::clear_has_down() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RadarReport::clear_down() {
  down_ = 0;
  clear_has_down();
}
inline float RadarReport::down() const {
  // @@protoc_insertion_point(field_get:RadarReport.down)
  return down_;
}
inline void RadarReport::set_down(float value) {
  set_has_down();
  down_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.down)
}

// required float latitude = 9;
inline bool RadarReport::has_latitude() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RadarReport::set_has_latitude() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RadarReport::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RadarReport::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline float RadarReport::latitude() const {
  // @@protoc_insertion_point(field_get:RadarReport.latitude)
  return latitude_;
}
inline void RadarReport::set_latitude(float value) {
  set_has_latitude();
  latitude_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.latitude)
}

// required float longitude = 10;
inline bool RadarReport::has_longitude() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RadarReport::set_has_longitude() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RadarReport::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RadarReport::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline float RadarReport::longitude() const {
  // @@protoc_insertion_point(field_get:RadarReport.longitude)
  return longitude_;
}
inline void RadarReport::set_longitude(float value) {
  set_has_longitude();
  longitude_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.longitude)
}

// required sfixed32 altitude = 11;
inline bool RadarReport::has_altitude() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RadarReport::set_has_altitude() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RadarReport::clear_has_altitude() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RadarReport::clear_altitude() {
  altitude_ = 0;
  clear_has_altitude();
}
inline ::google::protobuf::int32 RadarReport::altitude() const {
  // @@protoc_insertion_point(field_get:RadarReport.altitude)
  return altitude_;
}
inline void RadarReport::set_altitude(::google::protobuf::int32 value) {
  set_has_altitude();
  altitude_ = value;
  // @@protoc_insertion_point(field_set:RadarReport.altitude)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_radar_2eproto__INCLUDED
