// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcas.proto

#ifndef PROTOBUF_tcas_2eproto__INCLUDED
#define PROTOBUF_tcas_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tcas_2eproto();
void protobuf_AssignDesc_tcas_2eproto();
void protobuf_ShutdownFile_tcas_2eproto();

class TcasReport;

// ===================================================================

class TcasReport : public ::google::protobuf::Message {
 public:
  TcasReport();
  virtual ~TcasReport();

  TcasReport(const TcasReport& from);

  inline TcasReport& operator=(const TcasReport& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TcasReport& default_instance();

  void Swap(TcasReport* other);

  // implements Message ----------------------------------------------

  TcasReport* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TcasReport& from);
  void MergeFrom(const TcasReport& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required sfixed32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required sfixed32 range = 2;
  inline bool has_range() const;
  inline void clear_range();
  static const int kRangeFieldNumber = 2;
  inline ::google::protobuf::int32 range() const;
  inline void set_range(::google::protobuf::int32 value);

  // required sfixed32 altitude = 3;
  inline bool has_altitude() const;
  inline void clear_altitude();
  static const int kAltitudeFieldNumber = 3;
  inline ::google::protobuf::int32 altitude() const;
  inline void set_altitude(::google::protobuf::int32 value);

  // required sfixed32 bearing = 4;
  inline bool has_bearing() const;
  inline void clear_bearing();
  static const int kBearingFieldNumber = 4;
  inline ::google::protobuf::int32 bearing() const;
  inline void set_bearing(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TcasReport)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_range();
  inline void clear_has_range();
  inline void set_has_altitude();
  inline void clear_has_altitude();
  inline void set_has_bearing();
  inline void clear_has_bearing();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 range_;
  ::google::protobuf::int32 altitude_;
  ::google::protobuf::int32 bearing_;
  friend void  protobuf_AddDesc_tcas_2eproto();
  friend void protobuf_AssignDesc_tcas_2eproto();
  friend void protobuf_ShutdownFile_tcas_2eproto();

  void InitAsDefaultInstance();
  static TcasReport* default_instance_;
};
// ===================================================================


// ===================================================================

// TcasReport

// required sfixed32 id = 1;
inline bool TcasReport::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TcasReport::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TcasReport::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TcasReport::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 TcasReport::id() const {
  // @@protoc_insertion_point(field_get:TcasReport.id)
  return id_;
}
inline void TcasReport::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TcasReport.id)
}

// required sfixed32 range = 2;
inline bool TcasReport::has_range() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TcasReport::set_has_range() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TcasReport::clear_has_range() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TcasReport::clear_range() {
  range_ = 0;
  clear_has_range();
}
inline ::google::protobuf::int32 TcasReport::range() const {
  // @@protoc_insertion_point(field_get:TcasReport.range)
  return range_;
}
inline void TcasReport::set_range(::google::protobuf::int32 value) {
  set_has_range();
  range_ = value;
  // @@protoc_insertion_point(field_set:TcasReport.range)
}

// required sfixed32 altitude = 3;
inline bool TcasReport::has_altitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TcasReport::set_has_altitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TcasReport::clear_has_altitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TcasReport::clear_altitude() {
  altitude_ = 0;
  clear_has_altitude();
}
inline ::google::protobuf::int32 TcasReport::altitude() const {
  // @@protoc_insertion_point(field_get:TcasReport.altitude)
  return altitude_;
}
inline void TcasReport::set_altitude(::google::protobuf::int32 value) {
  set_has_altitude();
  altitude_ = value;
  // @@protoc_insertion_point(field_set:TcasReport.altitude)
}

// required sfixed32 bearing = 4;
inline bool TcasReport::has_bearing() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TcasReport::set_has_bearing() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TcasReport::clear_has_bearing() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TcasReport::clear_bearing() {
  bearing_ = 0;
  clear_has_bearing();
}
inline ::google::protobuf::int32 TcasReport::bearing() const {
  // @@protoc_insertion_point(field_get:TcasReport.bearing)
  return bearing_;
}
inline void TcasReport::set_bearing(::google::protobuf::int32 value) {
  set_has_bearing();
  bearing_ = value;
  // @@protoc_insertion_point(field_set:TcasReport.bearing)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tcas_2eproto__INCLUDED
