// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    public partial class TcasReport
    {
        public int Id { get; set; }

        /// <summary> ID of target</summary>
        public int Range { get; set; }

        /// <summary> relative distance</summary>
        public int Altitude { get; set; }

        /// <summary> relative altitude</summary>
        public int Bearing { get; set; }

    }

}
